### ISSUE TITLE
Import Compilation Error

### ISSUE THREAD

**Issue by yousefkhan** [nestjsx/nestjs-flub#21]
Trying to test this lib with my project. But I am getting the error on import.

![image](https://user-images.githubusercontent.com/36043054/51894645-302afb80-23ca-11e9-98fb-743541eb1065.png)
Inside index.ts also
![image](https://user-images.githubusercontent.com/36043054/51894815-90ba3880-23ca-11e9-887b-059d481b7de5.png)
it says `Cannot find module 'flub-error-handler'` and `Cannot find module 'error-handler'`

I have updated my dependencies too as mentioned in your package.json `peerDependencies`
`"@nestjs/common": "^5.4.0",
 "@nestjs/core": "^5.4.0"`.

Any help will be much appreciated. Let me know if I am missing anything

**Comment by bashleigh** [comment]
Does running tsc give you the same error? I think this is because there's no index.d.ts file in the package therefore the IDE can't find those exports. I'll have a look today and see if I can add one :)

**Comment by yousefkhan** [comment]
@bashleigh thank you for the quick response.
I am able to run `tsc` if I import like this
`import { FlubErrorHandler } from '../../node_modules/nestjs-flub/src/flub-error-handler';`
Otherwise it says `Cannot find module 'nestjs-flub'`

**Comment by bashleigh** [comment]
@yousefkhan so running `tsc` with `import {FlubErrorHandler} from 'flub-error-handler' results in an error?

**Comment by yousefkhan** [comment]
@bashleigh  Yes.
Running `import {FlubErrorHandler} from 'flub-error-handler'` results in error 

> Cannot find module 'flub-error-handler'

**Comment by bashleigh** [comment]
found the problem 👍

**Comment by maxfriedmann** [comment]
Whats the status @bashleigh? Just installed this good looking dependeny via npm and got this error!

**Comment by bashleigh** [comment]
@maxfriedmann sorry I've not managed to take a look at this :( been really busy! I'll try and find some time this week to take a look at it. Sorry!

**Comment by guotingchaopr** [comment]
Hasn't it been solved yet?

**Comment by bashleigh** [comment]
released as 0.2.0
